// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-predictions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_predictions_default = defineTool({
  name: "list_predictions",
  title: "List predictions",
  description: "List prediction markets on eCash Pulse. Filter by status (active, resolved, awaiting_resolution) and category. Returns title, pools, dates, and status.",
  inputSchema: {
    status: z.enum(["active", "resolved", "awaiting_resolution", "cancelled"]).optional().describe("Filter by market status. Omit for all statuses."),
    category: z.string().optional().describe("Filter by category (e.g. sports, crypto, politics)."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, category, limit }) => {
    let q = anonClient().from("predictions").select("id, title, description, category, status, yes_pool, no_pool, end_date, resolution_date, resolved_at, image_url, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { predictions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-prediction.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function anonClient2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_prediction_default = defineTool2({
  name: "get_prediction",
  title: "Get prediction",
  description: "Fetch a single prediction market by ID, including pools, status, and dates.",
  inputSchema: {
    id: z2.string().describe("Prediction market UUID.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const { data, error } = await anonClient2().from("predictions").select("id, title, description, category, status, yes_pool, no_pool, end_date, resolution_date, resolved_at, image_url, created_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Prediction not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prediction: data }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool3({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Fetch the eCash Pulse leaderboard: top users ranked by wins, winnings, and win rate.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.functions.invoke("get-leaderboard", {
      body: { limit }
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leaderboard: data }
    };
  }
});

// src/lib/mcp/tools/get-platform-stats.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_platform_stats_default = defineTool4({
  name: "get_platform_stats",
  title: "Get platform stats",
  description: "Fetch aggregate eCash Pulse platform statistics: total volume, users, markets, and bets.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.functions.invoke("get-platform-stats", { body: {} });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { stats: data }
    };
  }
});

// src/lib/mcp/tools/list-raffles.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_raffles_default = defineTool5({
  name: "list_raffles",
  title: "List raffles",
  description: "List active and past raffles on eCash Pulse, including ticket price and prize pool.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.functions.invoke("get-raffles", { body: { limit } });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { raffles: data }
    };
  }
});

// src/lib/mcp/tools/get-top-volume.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var get_top_volume_default = defineTool6({
  name: "get_top_volume_markets",
  title: "Get top volume markets",
  description: "Fetch the highest-volume prediction markets on eCash Pulse.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.functions.invoke("get-top-volume", { body: { limit } });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { markets: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ecash-pulse-mcp",
  title: "eCash Pulse MCP",
  version: "0.1.0",
  instructions: "Public read-only tools for eCash Pulse, a decentralized prediction market on eCash. Use these to browse prediction markets, the leaderboard, platform stats, top-volume markets, and raffles. No user or wallet data is exposed.",
  tools: [list_predictions_default, get_prediction_default, get_leaderboard_default, get_platform_stats_default, list_raffles_default, get_top_volume_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
